tosca_definitions_version: tosca_simple_yaml_1_3

imports:
  - cluster.yaml

capability_types:

  kubetos.capabilities.Kubernetes.Container:
    derived_from: tosca.capabilities.Root
    properties:
      name:
        type: string

node_types:

  kubetos.nodes.Kubernetes.Container:
    derived_from: tosca.nodes.Root
    capabilities:
      container:
        type: kubetos.capabilities.Kubernetes.Container
    properties:
      image:
        type: string

  kubetos.nodes.Kubernetes.Pod:
    derived_from: tosca.nodes.Root
    
  kubetos.nodes.Kubernetes.StaticPod:
    derived_from: kubetos.nodes.Kubernetes.Pod
    requirements:
      - host:
          capability: kubetos.capabilities.Kubelet
          relationship: tosca.relationships.HostedOn
      
    