---
- hosts: all
  gather_facts: no
  tasks:
  
  - name: get server info
    os_server_info:
      server: "{{ server_id }}"
    register: server_info

  - name: asdaa
    debug:
      msg: "{{ server_info }}"

  - name: Acquire floating IPs for instance
    os_floating_ip:
      state: present
      server: "{{ server_id }}"
      network: "{{ floating_ip_pool }}"
      reuse: yes
      wait: yes
    when: server_info.openstack_servers[0].public_v4 == ''

  - name: get server info
    os_server_info:
      server: "{{ server_id }}"
    register: server_info

  - name: Set public ip from acquired floating IP
    set_stats:
      data:
        ip_address: "{{ server_info.openstack_servers[0].public_v4 }}"
