---
- hosts: all
  gather_facts: no
  tasks:

  - name: retrieve info about image
    os_image_info:
      image: "{{ required_distro }}-{{ required_version }}"
    register: result

  - name: retrieve info about image with arch
    os_image_info:
      image: "{{ required_distro }}-{{ required_version }}-{{ required_arch }}"
    register: result
    when: result.openstack_images | length == 0


  - name: fail if there is no matching images
    fail:
      msg: "no matching images"
    when: result.openstack_images | length == 0

  - name: return id of the image
    set_stats:
      data:
        id: "{{ result.openstack_images[0].id }}"
    when: result.openstack_images | length > 0
