
  mycluster_sub_worker_sub_compute_sub_os_flavor: "Topology mycluster_sub_worker_sub_compute_sub_os_flavor" {
  
  node_os_flavor: "os_flavor\n(nova.Flavor)" {
  
    style { fill: honeydew }
    
  attributes {
    shape: class
  
    +state: "started"
    
    +tosca_id: "f3fda04b85cc4c479b7c0ae914dbbe90"
    
    +tosca_name: "os_flavor"
    
  }
  
  feature: "feature\n(tosca::Node)" {
  
  }
  
  flavor: "flavor\n(nova.Flavor)" {
  
  attributes {
    shape: class
  
    +openstack_id: "None"
    
  }
  
  }
  
  }
  
  }
  