
  mycluster_sub_control_plane_sub_compute_sub_os_image: "Topology mycluster_sub_control_plane_sub_compute_sub_os_image" {
  
  node_os_image: "os_image\n(glance.WebImage)" {
  
    style { fill: honeydew }
    
  attributes {
    shape: class
  
    +state: "started"
    
    +tosca_id: "34e903b399a448919090085d85d6d498"
    
    +tosca_name: "os_image"
    
  }
  
  feature: "feature\n(tosca::Node)" {
  
  }
  
  image: "image\n(glance.WebImage)" {
  
  attributes {
    shape: class
  
    +openstack_id: "None"
    
    \#architecture: "x86_64"
    
    \#distribution: "ubuntu"
    
    \#version: "20.04"
    
  }
  
  }
  
  }
  
  }
  