
  mycluster_sub_control_plane_sub_compute_sub_os_security_group_custom: "Topology mycluster_sub_control_plane_sub_compute_sub_os_security_group_custom" {
  
  node_os_security_group: "os_security_group\n(neutron.SecurityGroup)" {
  
    style { fill: honeydew }
    
  attributes {
    shape: class
  
    +state: "started"
    
    +tosca_id: "035d927e926447c885655a8daa9b385e"
    
    +tosca_name: "os_security_group"
    
  }
  
  feature: "feature\n(tosca::Node)" {
  
  }
  
  security_group: "security_group\n(neutron.SecurityGroup)" {
  
  attributes {
    shape: class
  
    \#name: "os_server-security-group"
    
  }
  
  }
  
  }
  
  }
  