
  mycluster_sub_worker_sub_compute: "Topology mycluster_sub_worker_sub_compute" {
  
  inputs {
    shape: class
  
    \#floating_ip_pool: ""
    
    \#key_name: ""
    
  }
  
  node_os_flavor: "os_flavor\n(nova.Flavor)" {
  
    link: "./mycluster_sub_worker_sub_compute_sub_os_flavor.svg"
    
  attributes {
    shape: class
  
    +state: "started"
    
    +tosca_id: "6fd922be0a2e4fc294899b3d8debbac7"
    
    +tosca_name: "os_flavor"
    
  }
  
  feature: "feature\n(tosca::Node)" {
  
  }
  
  flavor: "flavor\n(nova.Flavor)" {
  
  attributes {
    shape: class
  
    +openstack_id: "None"
    
  }
  
  }
  
  }
  
  node_os_floating_ip: "os_floating_ip\n(neutron.FloatingIp)" {
  
    link: "./mycluster_sub_worker_sub_compute_sub_os_floating_ip.svg"
    
  attributes {
    shape: class
  
    +state: "started"
    
    +tosca_id: "a893dbf6d5bf49aa8889721de933a132"
    
    +tosca_name: "os_floating_ip"
    
  }
  
  endpoint: "endpoint\n(neutron.FloatingIp)" {
  
  attributes {
    shape: class
  
    \#initiator: "source"
    
    \#network_name: ""
    
    \#protocol: "tcp"
    
    \#secure: "False"
    
    +ip_address: "None"
    
  }
  
  }
  
  feature: "feature\n(tosca::Node)" {
  
  }
  
  rel_nova_server: "nova_server\n(FloatingIpToCompute)" {
    shape: parallelogram
  
  attributes {
    shape: class
  
    +state: "initial"
    
    +tosca_id: "None"
    
    +tosca_name: "None"
    
  }
  
  }
  
  }
  
  node_os_image: "os_image\n(glance.WebImage)" {
  
    link: "./mycluster_sub_worker_sub_compute_sub_os_image.svg"
    
  attributes {
    shape: class
  
    +state: "started"
    
    +tosca_id: "7a4400ead68948a49a7bc24cfd01771f"
    
    +tosca_name: "os_image"
    
  }
  
  feature: "feature\n(tosca::Node)" {
  
  }
  
  image: "image\n(glance.WebImage)" {
  
  attributes {
    shape: class
  
    +openstack_id: "None"
    
  }
  
  }
  
  }
  
  node_os_key_pair: "os_key_pair\n(nova.KeyPair)" {
  
  attributes {
    shape: class
  
    +state: "started"
    
    +tosca_id: "67671af75ff148479556896879816e26"
    
    +tosca_name: "os_key_pair"
    
  }
  
  feature: "feature\n(tosca::Node)" {
  
  }
  
  key_pair: "key_pair\n(nova.KeyPair)" {
  
  attributes {
    shape: class
  
    \#name: ""
    
  }
  
  }
  
  }
  
  node_os_security_group_custom: "os_security_group_custom\n(neutron.SecurityGroup)" {
  
    link: "./mycluster_sub_worker_sub_compute_sub_os_security_group_custom.svg"
    
  attributes {
    shape: class
  
    +state: "started"
    
    +tosca_id: "153d80ba0bdd44bdaec31cfa0a923cfe"
    
    +tosca_name: "os_security_group_custom"
    
  }
  
  feature: "feature\n(tosca::Node)" {
  
  }
  
  security_group: "security_group\n(neutron.SecurityGroup)" {
  
  attributes {
    shape: class
  
    \#name: "os_server-security-group"
    
  }
  
  }
  
  }
  
  node_os_security_group_custom_rule_incoming_tcp_traffic: "os_security_group_custom_rule_incoming_tcp_traffic\n(neutron.SecurityGroupRule)" {
  
    link: "./mycluster_sub_worker_sub_compute_sub_os_security_group_custom_rule_incoming_tcp_traffic.svg"
    
  attributes {
    shape: class
  
    \#direction: "ingress"
    
    \#ethertype: "IPv4"
    
    \#protocol: "tcp"
    
    \#remote_ip_prefix: "0.0.0.0/0"
    
    +state: "started"
    
    +tosca_id: "6fe9357f7ad84b16b389fcf8b0830ac9"
    
    +tosca_name: "os_security_group_custom_rule_incoming_tcp_traffic"
    
  }
  
  feature: "feature\n(tosca::Node)" {
  
  }
  
  rel_security_group: "security_group\n(tosca::DependsOn)" {
    shape: parallelogram
  
  attributes {
    shape: class
  
    +state: "initial"
    
    +tosca_id: "None"
    
    +tosca_name: "None"
    
  }
  
  }
  
  }
  
  node_os_security_group_default: "os_security_group_default\n(neutron.SecurityGroup)" {
  
  attributes {
    shape: class
  
    +state: "started"
    
    +tosca_id: "73c0f52afcb94eb988acd88f83744043"
    
    +tosca_name: "os_security_group_default"
    
  }
  
  feature: "feature\n(tosca::Node)" {
  
  }
  
  security_group: "security_group\n(neutron.SecurityGroup)" {
  
  attributes {
    shape: class
  
    \#name: "default"
    
  }
  
  }
  
  }
  
  node_os_server: "os_server\n(nova.Server)" {
  
    link: "./mycluster_sub_worker_sub_compute_sub_os_server.svg"
    
  attributes {
    shape: class
  
    +networks: "None"
    
    +ports: "None"
    
    +private_address: "None"
    
    +public_address: "None"
    
    +security_groups: "None"
    
    +state: "started"
    
    +tosca_id: "e308f5ce301e4ffbaa246a4bc860ce03"
    
    +tosca_name: "os_server"
    
  }
  
  binding: "binding\n(tosca::Bindable)" {
  
  }
  
  feature: "feature\n(tosca::Node)" {
  
  }
  
  private_endpoint: "private_endpoint\n(tosca::Endpoint)" {
  
  attributes {
    shape: class
  
    \#initiator: "source"
    
    \#network_name: "PRIVATE"
    
    \#protocol: "tcp"
    
    \#secure: "False"
    
    +ip_address: "None"
    
  }
  
  }
  
  scalable: "scalable\n(tosca::Scalable)" {
  
  attributes {
    shape: class
  
    \#max_instances: "1"
    
    \#min_instances: "1"
    
  }
  
  }
  
  server: "server\n(nova.Server)" {
  
  attributes {
    shape: class
  
    +openstack_id: "None"
    
  }
  
  }
  
  rel_image: "image\n(tosca::DependsOn)" {
    shape: parallelogram
  
  attributes {
    shape: class
  
    +state: "initial"
    
    +tosca_id: "None"
    
    +tosca_name: "None"
    
  }
  
  }
  
  rel_flavor: "flavor\n(tosca::DependsOn)" {
    shape: parallelogram
  
  attributes {
    shape: class
  
    +state: "initial"
    
    +tosca_id: "None"
    
    +tosca_name: "None"
    
  }
  
  }
  
  rel_key_pair: "key_pair\n(tosca::DependsOn)" {
    shape: parallelogram
  
  attributes {
    shape: class
  
    +state: "initial"
    
    +tosca_id: "None"
    
    +tosca_name: "None"
    
  }
  
  }
  
  rel_security_group: "security_group\n(ComputeToSecurityGroup)" {
    shape: parallelogram
  
  attributes {
    shape: class
  
    +state: "initial"
    
    +tosca_id: "None"
    
    +tosca_name: "None"
    
  }
  
  }
  
  rel_security_group: "security_group\n(ComputeToSecurityGroup)" {
    shape: parallelogram
  
  attributes {
    shape: class
  
    +state: "initial"
    
    +tosca_id: "None"
    
    +tosca_name: "None"
    
  }
  
  }
  
  }
  
  }
  
      mycluster_sub_worker_sub_compute { link: "./mycluster_sub_worker_sub_compute.svg" }
      mycluster_sub_worker_sub_compute.node_os_floating_ip.rel_nova_server -> mycluster_sub_worker_sub_compute.node_os_server
      
      mycluster_sub_worker_sub_compute { link: "./mycluster_sub_worker_sub_compute.svg" }
      mycluster_sub_worker_sub_compute.node_os_security_group_custom_rule_incoming_tcp_traffic.rel_security_group -> mycluster_sub_worker_sub_compute.node_os_security_group_custom
      
      mycluster_sub_worker_sub_compute { link: "./mycluster_sub_worker_sub_compute.svg" }
      mycluster_sub_worker_sub_compute.node_os_server.rel_image -> mycluster_sub_worker_sub_compute.node_os_image
      
      mycluster_sub_worker_sub_compute { link: "./mycluster_sub_worker_sub_compute.svg" }
      mycluster_sub_worker_sub_compute.node_os_server.rel_flavor -> mycluster_sub_worker_sub_compute.node_os_flavor
      
      mycluster_sub_worker_sub_compute { link: "./mycluster_sub_worker_sub_compute.svg" }
      mycluster_sub_worker_sub_compute.node_os_server.rel_key_pair -> mycluster_sub_worker_sub_compute.node_os_key_pair
      
      mycluster_sub_worker_sub_compute { link: "./mycluster_sub_worker_sub_compute.svg" }
      mycluster_sub_worker_sub_compute.node_os_server.rel_security_group -> mycluster_sub_worker_sub_compute.node_os_security_group_default
      
      mycluster_sub_worker_sub_compute { link: "./mycluster_sub_worker_sub_compute.svg" }
      mycluster_sub_worker_sub_compute.node_os_server.rel_security_group -> mycluster_sub_worker_sub_compute.node_os_security_group_custom
      