
  mycluster_sub_control_plane_sub_compute_sub_os_floating_ip: "Topology mycluster_sub_control_plane_sub_compute_sub_os_floating_ip" {
  
  node_os_floating_ip: "os_floating_ip\n(neutron.FloatingIp)" {
  
    style { fill: honeydew }
    
  attributes {
    shape: class
  
    +state: "started"
    
    +tosca_id: "8ccb899b443c42f89b97fccbbc5d6267"
    
    +tosca_name: "os_floating_ip"
    
  }
  
  endpoint: "endpoint\n(neutron.FloatingIp)" {
  
  attributes {
    shape: class
  
    \#initiator: "source"
    
    \#network_name: ""
    
    \#protocol: "tcp"
    
    \#secure: "False"
    
    +ip_address: "None"
    
  }
  
  }
  
  feature: "feature\n(tosca::Node)" {
  
  }
  
  rel_nova_server: "nova_server\n(FloatingIpToCompute)" {
    shape: parallelogram
  
  attributes {
    shape: class
  
    +state: "initial"
    
    +tosca_id: "None"
    
    +tosca_name: "None"
    
  }
  
  }
  
  }
  
  }
  
      mycluster_sub_control_plane_sub_compute { link: "./mycluster_sub_control_plane_sub_compute.svg" }
      mycluster_sub_control_plane_sub_compute_sub_os_floating_ip.node_os_floating_ip.rel_nova_server -> mycluster_sub_control_plane_sub_compute.node_os_server
      