
  mycluster_sub_worker: "Topology mycluster_sub_worker" {
  
  inputs {
    shape: class
  
    \#kubelet_version: "None"
    
  }
  
  node_cni: "cni\n(kubetos.nodes.CNI)" {
  
    link: "./mycluster_sub_worker_sub_cni.svg"
    
  attributes {
    shape: class
  
    \#component_version: "1.0.1"
    
    +state: "started"
    
    +tosca_id: "4d880cf8bfee4054913941a0a733f877"
    
    +tosca_name: "cni"
    
  }
  
  cni: "cni\n(kubetos.capabilities.CNI)" {
  
  attributes {
    shape: class
  
    \#binary_dir: "/opt/cni/bin"
    
    \#config_dir: "/etc/cni/net.d"
    
  }
  
  }
  
  feature: "feature\n(tosca::Node)" {
  
  }
  
  rel_host: "host\n(tosca::HostedOn)" {
    shape: parallelogram
  
  attributes {
    shape: class
  
    +state: "initial"
    
    +tosca_id: "None"
    
    +tosca_name: "None"
    
  }
  
  }
  
  }
  
  node_compute: "compute\n(tosca::Compute)" {
  
    link: "./mycluster_sub_worker_sub_compute.svg"
    
  attributes {
    shape: class
  
    +networks: "None"
    
    +ports: "None"
    
    +private_address: "None"
    
    +public_address: "None"
    
    +state: "started"
    
    +tosca_id: "97924ace9d81444994bd4d9d1394fb75"
    
    +tosca_name: "os_server"
    
  }
  
  binding: "binding\n(tosca::Bindable)" {
  
  }
  
  endpoint: "endpoint\n(tosca::Endpoint.Admin)" {
  
  attributes {
    shape: class
  
    \#initiator: "source"
    
    \#network_name: "PRIVATE"
    
    \#protocol: "tcp"
    
    \#secure: "False"
    
    +ip_address: "None"
    
  }
  
  }
  
  feature: "feature\n(tosca::Node)" {
  
  }
  
  host: "host\n(tosca::Compute)" {
  
  }
  
  os: "os\n(tosca::OperatingSystem)" {
  
  }
  
  scalable: "scalable\n(tosca::Scalable)" {
  
  attributes {
    shape: class
  
    \#max_instances: "1"
    
    \#min_instances: "1"
    
  }
  
  }
  
  }
  
  node_cri: "cri\n(kubetos.nodes.CRI)" {
  
    link: "./mycluster_sub_worker_sub_cri.svg"
    
  attributes {
    shape: class
  
    +runtimes: "None"
    
    +state: "started"
    
    +tosca_id: "c9131faa33b2481ab2e1a0ab32e23cb4"
    
    +tosca_name: "cri"
    
  }
  
  cri: "cri\n(kubetos.capabilities.CRI)" {
  
  attributes {
    shape: class
  
    \#initiator: "source"
    
    \#network_name: "PRIVATE"
    
    \#protocol: "rpc"
    
    \#secure: "False"
    
    +ip_address: "None"
    
  }
  
  }
  
  feature: "feature\n(tosca::Node)" {
  
  }
  
  rel_host: "host\n(tosca::HostedOn)" {
    shape: parallelogram
  
  attributes {
    shape: class
  
    +state: "initial"
    
    +tosca_id: "None"
    
    +tosca_name: "None"
    
  }
  
  }
  
  rel_cni: "cni\n(tosca::DependsOn)" {
    shape: parallelogram
  
  attributes {
    shape: class
  
    +state: "initial"
    
    +tosca_id: "None"
    
    +tosca_name: "None"
    
  }
  
  }
  
  rel_oci_runtime: "oci_runtime\n(kubetos.relationships.OCI.Plugin)" {
    shape: parallelogram
  
  attributes {
    shape: class
  
    +state: "initial"
    
    +tosca_id: "None"
    
    +tosca_name: "None"
    
  }
  
  }
  
  }
  
  node_etcd: "etcd\n(kubetos.nodes.Etcd)" {
  
    link: "./mycluster_sub_worker_sub_etcd.svg"
    
  attributes {
    shape: class
  
    \#backup_retention_count: "-1"
    
    \#component_version: "3.4.13"
    
    \#election_timeout: "5"
    
    \#heartbeat_interval: "0.25"
    
    \#max_snapshots: "0"
    
    \#max_wals: "0"
    
    \#quota_backend_bytes: "2147483648"
    
    \#snapshot_count: "10000"
    
    +name: "07b78b933708423a810d8dec53b350b5"
    
    +peers: "None"
    
    +state: "started"
    
    +tosca_id: "07b78b933708423a810d8dec53b350b5"
    
    +tosca_name: "etcd"
    
  }
  
  access_address: "access_address\n(kubetos.capabilities.Etcd.Endpoint.Access)" {
  
  attributes {
    shape: class
  
    \#api_version: "v2"
    
    \#initiator: "source"
    
    \#network_name: "PRIVATE"
    
    \#port: "2379"
    
    \#protocol: "tcp"
    
    \#secure: "False"
    
    +ip_address: "None"
    
  }
  
  }
  
  feature: "feature\n(tosca::Node)" {
  
  }
  
  peer_address: "peer_address\n(kubetos.capabilities.Etcd.Endpoint.Peer)" {
  
  attributes {
    shape: class
  
    \#initiator: "source"
    
    \#network_name: "PRIVATE"
    
    \#port: "2380"
    
    \#protocol: "tcp"
    
    \#secure: "False"
    
    +ip_address: "None"
    
  }
  
  }
  
  rel_host: "host\n(tosca::HostedOn)" {
    shape: parallelogram
  
  attributes {
    shape: class
  
    +state: "initial"
    
    +tosca_id: "None"
    
    +tosca_name: "None"
    
  }
  
  }
  
  }
  
  node_kubelet: "kubelet\n(kubetos.nodes.Kubernetes.Kubelet)" {
  
    link: "./mycluster_sub_worker_sub_kubelet.svg"
    
  attributes {
    shape: class
  
    \#component_version: "None"
    
    +state: "started"
    
    +tosca_id: "bf484308cb1b4f2897394ea93074adad"
    
    +tosca_name: "kubelet"
    
  }
  
  feature: "feature\n(tosca::Node)" {
  
  }
  
  kubelet: "kubelet\n(kubetos.capabilities.Kubelet)" {
  
  }
  
  rel_cri_runtime: "cri_runtime\n(kubetos.relationships.Kubelet.UsesRuntime)" {
    shape: parallelogram
  
  attributes {
    shape: class
  
    +state: "initial"
    
    +tosca_id: "None"
    
    +tosca_name: "None"
    
  }
  
  }
  
  rel_host: "host\n(tosca::HostedOn)" {
    shape: parallelogram
  
  attributes {
    shape: class
  
    +state: "initial"
    
    +tosca_id: "None"
    
    +tosca_name: "None"
    
  }
  
  }
  
  rel_apiserver: "apiserver\n(tosca::ConnectsTo)" {
    shape: parallelogram
  
  attributes {
    shape: class
  
    +state: "initial"
    
    +tosca_id: "None"
    
    +tosca_name: "None"
    
  }
  
  }
  
  }
  
  node_oci_runtime: "oci_runtime\n(kubetos.nodes.OCI.Runtime)" {
  
    link: "./mycluster_sub_worker_sub_oci_runtime.svg"
    
  attributes {
    shape: class
  
    +state: "started"
    
    +tosca_id: "393f164249904cc48a6accf931586219"
    
    +tosca_name: "oci_runtime"
    
  }
  
  feature: "feature\n(tosca::Node)" {
  
  }
  
  oci: "oci\n(kubetos.capabilities.OCI.Runtime)" {
  
  }
  
  rel_host: "host\n(tosca::HostedOn)" {
    shape: parallelogram
  
  attributes {
    shape: class
  
    +state: "initial"
    
    +tosca_id: "None"
    
    +tosca_name: "None"
    
  }
  
  }
  
  }
  
  }
  
      mycluster_sub_worker { link: "./mycluster_sub_worker.svg" }
      mycluster_sub_worker.node_cni.rel_host -> mycluster_sub_worker.node_compute
      
      mycluster_sub_worker { link: "./mycluster_sub_worker.svg" }
      mycluster_sub_worker.node_cri.rel_host -> mycluster_sub_worker.node_compute
      
      mycluster_sub_worker { link: "./mycluster_sub_worker.svg" }
      mycluster_sub_worker.node_cri.rel_cni -> mycluster_sub_worker.node_cni
      
      mycluster_sub_worker { link: "./mycluster_sub_worker.svg" }
      mycluster_sub_worker.node_cri.rel_oci_runtime -> mycluster_sub_worker.node_oci_runtime
      
      mycluster_sub_worker { link: "./mycluster_sub_worker.svg" }
      mycluster_sub_worker.node_etcd.rel_host -> mycluster_sub_worker.node_compute
      
      mycluster_sub_worker { link: "./mycluster_sub_worker.svg" }
      mycluster_sub_worker.node_kubelet.rel_cri_runtime -> mycluster_sub_worker.node_cri
      
      mycluster_sub_worker { link: "./mycluster_sub_worker.svg" }
      mycluster_sub_worker.node_kubelet.rel_host -> mycluster_sub_worker.node_compute
      
      mycluster { link: "./mycluster.svg" }
      mycluster_sub_worker.node_kubelet.rel_apiserver -> mycluster.node_control_plane
      
      mycluster_sub_worker { link: "./mycluster_sub_worker.svg" }
      mycluster_sub_worker.node_oci_runtime.rel_host -> mycluster_sub_worker.node_compute
      