
  mycluster_sub_control_plane_sub_kubelet: "Topology mycluster_sub_control_plane_sub_kubelet" {
  
  inputs {
    shape: class
  
    \#component_version: "None"
    
    \#dns_ip: "None"
    
    \#pod_cidr: "None"
    
  }
  
  node_kubelet: "kubelet\n(kubetos.nodes.Kubernetes.Kubelet)" {
  
    style { fill: honeydew }
    
  attributes {
    shape: class
  
    \#component_version: "None"
    
    +state: "started"
    
    +tosca_id: "541903877e48465e9f986c6b16e5c7f8"
    
    +tosca_name: "kubelet"
    
  }
  
  feature: "feature\n(tosca::Node)" {
  
  }
  
  kubelet: "kubelet\n(kubetos.capabilities.Kubelet)" {
  
  }
  
  rel_apiserver: "apiserver\n(tosca::ConnectsTo)" {
    shape: parallelogram
  
  attributes {
    shape: class
  
    +state: "initial"
    
    +tosca_id: "None"
    
    +tosca_name: "None"
    
  }
  
  }
  
  rel_cri_runtime: "cri_runtime\n(kubetos.relationships.Kubelet.UsesRuntime)" {
    shape: parallelogram
  
  attributes {
    shape: class
  
    +state: "initial"
    
    +tosca_id: "None"
    
    +tosca_name: "None"
    
  }
  
  }
  
  rel_host: "host\n(tosca::HostedOn)" {
    shape: parallelogram
  
  attributes {
    shape: class
  
    +state: "initial"
    
    +tosca_id: "None"
    
    +tosca_name: "None"
    
  }
  
  }
  
  }
  
  }
  
      mycluster_sub_control_plane { link: "./mycluster_sub_control_plane.svg" }
      mycluster_sub_control_plane_sub_kubelet.node_kubelet.rel_apiserver -> mycluster_sub_control_plane.node_compute
      
      mycluster_sub_control_plane { link: "./mycluster_sub_control_plane.svg" }
      mycluster_sub_control_plane_sub_kubelet.node_kubelet.rel_cri_runtime -> mycluster_sub_control_plane.node_cri
      
      mycluster_sub_control_plane { link: "./mycluster_sub_control_plane.svg" }
      mycluster_sub_control_plane_sub_kubelet.node_kubelet.rel_host -> mycluster_sub_control_plane.node_compute
      