
  mycluster_sub_worker_sub_compute_sub_os_image: "Topology mycluster_sub_worker_sub_compute_sub_os_image" {
  
  node_os_image: "os_image\n(glance.WebImage)" {
  
    style { fill: honeydew }
    
  attributes {
    shape: class
  
    +state: "started"
    
    +tosca_id: "ce1a5169339f4a29aaccbf9112aadf63"
    
    +tosca_name: "os_image"
    
  }
  
  feature: "feature\n(tosca::Node)" {
  
  }
  
  image: "image\n(glance.WebImage)" {
  
  attributes {
    shape: class
  
    +openstack_id: "None"
    
  }
  
  }
  
  }
  
  }
  