
  mycluster_sub_control_plane_sub_compute_sub_os_flavor: "Topology mycluster_sub_control_plane_sub_compute_sub_os_flavor" {
  
  node_os_flavor: "os_flavor\n(nova.Flavor)" {
  
    style { fill: honeydew }
    
  attributes {
    shape: class
  
    +state: "started"
    
    +tosca_id: "a3f21fd0e3b7487baf34af610887a7d2"
    
    +tosca_name: "os_flavor"
    
  }
  
  feature: "feature\n(tosca::Node)" {
  
  }
  
  flavor: "flavor\n(nova.Flavor)" {
  
  attributes {
    shape: class
  
    +openstack_id: "None"
    
    \#disk_size: "10737418240"
    
    \#mem_size: "1073741824"
    
    \#num_cpus: "1"
    
  }
  
  }
  
  }
  
  }
  