
  test_sub_control_plane_sub_compute_sub_os_floating_ip: "Topology test_sub_control_plane_sub_compute_sub_os_floating_ip" {
  
  node_os_floating_ip: "os_floating_ip\n(neutron.FloatingIp)" {
  
    style { fill: green }
    
  attributes {
    shape: class
  
    +state: "initial"
    
    +tosca_id: "b1e220371768459f990d43dcf8636705"
    
    +tosca_name: "os_floating_ip"
    
  }
  
  endpoint: "endpoint\n(neutron.FloatingIp)" {
  
  attributes {
    shape: class
  
    \#initiator: "source"
    
    \#network_name: ""
    
    \#protocol: "tcp"
    
    \#secure: "False"
    
    +ip_address: "None"
    
  }
  
  }
  
  feature: "feature\n(tosca::Node)" {
  
  }
  
  rel_nova_server: "nova_server\n(FloatingIpToCompute)" {
    shape: parallelogram
  
  attributes {
    shape: class
  
    +state: "initial"
    
    +tosca_id: "None"
    
    +tosca_name: "None"
    
  }
  
  }
  
  }
  
  }
  
      test_sub_control_plane_sub_compute { link: "./test_sub_control_plane_sub_compute.svg" }
      test_sub_control_plane_sub_compute_sub_os_floating_ip.node_os_floating_ip.rel_nova_server -> test_sub_control_plane_sub_compute.node_os_server
      