
  test_sub_control_plane_sub_compute_sub_os_security_group_custom_rule_incoming_tcp_traffic: "Topology test_sub_control_plane_sub_compute_sub_os_security_group_custom_rule_incoming_tcp_traffic" {
  
  inputs {
    shape: class
  
    \#direction: "ingress"
    
    \#ethertype: "IPv4"
    
    \#port_range_max: "None"
    
    \#port_range_min: "None"
    
    \#protocol: "tcp"
    
    \#remote_ip_prefix: "0.0.0.0/0"
    
  }
  
  node_os_security_group_rule: "os_security_group_rule\n(neutron.SecurityGroupRule)" {
  
    style { fill: green }
    
  attributes {
    shape: class
  
    \#direction: "ingress"
    
    \#ethertype: "IPv4"
    
    \#port_range_max: "None"
    
    \#port_range_min: "None"
    
    \#protocol: "tcp"
    
    \#remote_ip_prefix: "0.0.0.0/0"
    
    +state: "initial"
    
    +tosca_id: "335a6547896047069a7cb2f78c816229"
    
    +tosca_name: "os_security_group_rule"
    
  }
  
  feature: "feature\n(tosca::Node)" {
  
  }
  
  rel_security_group: "security_group\n(tosca::DependsOn)" {
    shape: parallelogram
  
  attributes {
    shape: class
  
    +state: "initial"
    
    +tosca_id: "None"
    
    +tosca_name: "None"
    
  }
  
  }
  
  }
  
  }
  
      test_sub_control_plane_sub_compute { link: "./test_sub_control_plane_sub_compute.svg" }
      test_sub_control_plane_sub_compute_sub_os_security_group_custom_rule_incoming_tcp_traffic.node_os_security_group_rule.rel_security_group -> test_sub_control_plane_sub_compute.node_os_security_group_custom
      