
  test_sub_worker: "Topology test_sub_worker" {
  
  inputs {
    shape: class
  
    \#dns_ip: "10.32.0.3"
    
    \#kubernetes_version: "None"
    
    \#pod_cidr: "10.233.0.0/16"
    
    \#service_cidr: "10.32.0.0/16"
    
  }
  
  node_compute: "compute\n(tosca::Compute)" {
  
  attributes {
    shape: class
  
    +networks: "None"
    
    +ports: "None"
    
    +private_address: "None"
    
    +public_address: "None"
    
    +state: "initial"
    
    +tosca_id: "e10d4a664b5a43989b7a21faed810d41"
    
    +tosca_name: "compute"
    
  }
  
  binding: "binding\n(tosca::Bindable)" {
  
  }
  
  endpoint: "endpoint\n(tosca::Endpoint.Admin)" {
  
  attributes {
    shape: class
  
    \#initiator: "source"
    
    \#network_name: "PRIVATE"
    
    \#protocol: "tcp"
    
    \#secure: "True"
    
    +ip_address: "None"
    
  }
  
  }
  
  feature: "feature\n(tosca::Node)" {
  
  }
  
  host: "host\n(tosca::Compute)" {
  
  }
  
  os: "os\n(tosca::OperatingSystem)" {
  
  }
  
  scalable: "scalable\n(tosca::Scalable)" {
  
  attributes {
    shape: class
  
    \#max_instances: "1"
    
    \#min_instances: "1"
    
  }
  
  }
  
  }
  
  node_kube_node: "kube_node\n(kubetos.nodes.Kubernetes.Node)" {
  
    link: "./test_sub_worker_sub_kube_node.svg"
    
  attributes {
    shape: class
  
    \#component_version: "None"
    
    +state: "initial"
    
    +tosca_id: "919c9141fae849e6b5ceb298498ad7ca"
    
    +tosca_name: "kube_node"
    
  }
  
  client_cert: "client_cert\n(kubetos.capabilities.Certificate)" {
  
  attributes {
    shape: class
  
    \#common_name: "system:node:compute"
    
    \#hostnames: "['compute', None, None, '127.0.0.1']"
    
    \#organisation: "system:nodes"
    
    +cert: "None"
    
    +key: "None"
    
  }
  
  }
  
  endpoint: "endpoint\n(tosca::Endpoint)" {
  
  attributes {
    shape: class
  
    \#initiator: "source"
    
    \#network_name: "PRIVATE"
    
    \#protocol: "tcp"
    
    \#secure: "False"
    
    +ip_address: "None"
    
  }
  
  }
  
  feature: "feature\n(tosca::Node)" {
  
  }
  
  kubelet: "kubelet\n(kubetos.capabilities.Kubelet)" {
  
  }
  
  rel_host: "host\n(tosca::HostedOn)" {
    shape: parallelogram
  
  attributes {
    shape: class
  
    +state: "initial"
    
    +tosca_id: "None"
    
    +tosca_name: "None"
    
  }
  
  }
  
  rel_apiserver: "apiserver\n(tosca::ConnectsTo)" {
    shape: parallelogram
  
  attributes {
    shape: class
  
    +state: "initial"
    
    +tosca_id: "None"
    
    +tosca_name: "None"
    
  }
  
  }
  
  }
  
  }
  
      test_sub_worker { link: "./test_sub_worker.svg" }
      test_sub_worker.node_kube_node.rel_host -> test_sub_worker.node_compute
      
      test { link: "./test.svg" }
      test_sub_worker.node_kube_node.rel_apiserver -> test.node_control_plane
      