tosca_definitions_version: tosca_simple_yaml_1_3

metadata:
  template_name: "kubetos"
  template_author: "shishqa"
  template_version: "1.0"

imports:
  #- ../profiles/etcd/main.yaml
  - ../../profiles/kubernetes/cluster.yaml

topology_template:

  inputs:

    kubernetes_version:
      type: version

    cluster_name:
      type: string

    pod_cidr:
      type: string
      default: 10.233.0.0/16

    service_cidr:
      type: string
      default: 10.32.0.0/16

    dns_ip:
      type: string
      default: 10.32.0.3

  node_templates:

    worker:
      type: kubetos.nodes.Kubernetes.Worker
      directives: [ substitute ]
      properties:
        kubernetes_version: { get_input: [ kubernetes_version ] }
      requirements:
        - apiserver: control_plane

    control_plane:
      type: kubetos.nodes.Kubernetes.ControlPlane
      directives: [ substitute ]
      properties:
        kubernetes_version: { get_input: [ kubernetes_version ] }
        cluster_name: { get_input: [ cluster_name ] }
        service_cidr: { get_input: [ service_cidr ] }
        pod_cidr: { get_input: [ pod_cidr ] }

  substitution_mappings:
    node_type: kubetos.nodes.Kubernetes.Cluster
    capabilities:
      access_address: [ control_plane, access_address ]
    properties:
      kubernetes_version: [ kubernetes_version ]
      cluster_name: [ cluster_name ]
